require("kinoko.plugins-setup")
require("kinoko.core.options")
require("kinoko.core.keymaps")
require("kinoko.core.colorscheme")
require("kinoko.plugins.comment")
require("kinoko.plugins.nvim-tree")
require("kinoko.plugins.lualine")
require("kinoko.plugins.telescope")
-- require("kinoko.plugins.nvim-cmp")
require("kinoko.plugins.lsp")
require("kinoko.plugins.autopairs")
require("kinoko.plugins.mason")
require("kinoko.plugins.null-ls")
require("kinoko.plugins.gitsigns")
require("kinoko.plugins.tree-sitter")
